version: '3.8'  # Añade la versión al inicio

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: com600_t3_3_compra_entradas_service
    container_name: com600_t3_3_compra_entradas_service
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www 
    networks:
      - app-network
    depends_on:
      - mysql
      # Si necesitas RabbitMQ, descomenta la siguiente línea
      # - rabbitmq

  nginx:
    image: nginx:stable-alpine
    container_name: compra_entradas_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: compra_entradas_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: compra_entradas_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  # Si necesitas RabbitMQ, añade este servicio
  rabbitmq:
    image: rabbitmq:3-management
    container_name: compra_entradas_rabbitmq
    ports:
      - "5672:5672"  # Puerto para AMQP
      - "15672:15672"  # Puerto para la interfaz de gestión
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge