version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: com600_t3_3_compra_entradas_service
    container_name: com600_t3_3_compra_entradas_service
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www 
    networks:
      - app-network
    depends_on:
      - mysql
      # - rabbitmq

  nginx:
    image: nginx:stable-alpine
    container_name: compra_entradas_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    networks:
      - app-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: compra_entradas_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: compra_entradas_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge