# docker-compose.yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: compra-entradas-app
    container_name: compra_entradas_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www      # Montar código al contenedor
    networks:
      - app-network
    depends_on:
      - mysql

  nginx:
    image: nginx:stable-alpine
    container_name: compra_entradas_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: compra_entradas_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: compra_entradas_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
