version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mservicio_compras_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8003:8000"
    networks:
      - compras_network
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=compras_db
      - DB_USERNAME=compras_user
      - DB_PASSWORD=compras_pass

  mysql:
    image: mysql:8.0
    container_name: mservicio_compras_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: compras_db
      MYSQL_USER: compras_user
      MYSQL_PASSWORD: compras_pass
      MYSQL_ROOT_PASSWORD: root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - compras_network

networks:
  compras_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local