# Usar una imagen base de Node.js
FROM node:20-alpine

# Directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos de dependencias e instalar
COPY package.json .
COPY package-lock.json .
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Exponer el puerto de la aplicación
EXPOSE 3000

# Comando para iniciar la API
CMD ["npm", "start"]
