services:
  db:
    image: mysql:8.0
    container_name: login_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: login_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  login-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: login_service
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  db_data:
