version: '3.8'

services:


  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    networks:
      - backend-net

  frontend-service:
    build: ./frontend
    container_name: frontend-service
    depends_on:
      - usuarios-service
      - reservas-service
    networks:
      - backend-net




  usuarios-db:
    image: mysql:8
    container_name: usuarios-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: usuariosdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - usuarios_db_data:/var/lib/mysql
    networks:
      - backend-net

  usuarios-service:
    build: ./services/usuarios-service
    container_name: usuarios-service
    env_file: ./services/usuarios-service/.env
    depends_on:
      - usuarios-db
    ports:
      - "4001:3001"
    networks:
      - backend-net

  reservas-db:
    image: postgres:13
    container_name: reservas-db
    environment:
      POSTGRES_DB: reservasdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - reservas_db_data:/var/lib/postgresql/data
    networks:
      - backend-net

  reservas-service:
    build: ./services/reservas-service
    container_name: reservas-service
    env_file: ./services/reservas-service/.env
    depends_on:
      - reservas-db
      - usuarios-service
    ports:
      - "4002:8000"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  usuarios_db_data:
  reservas_db_data:
