services:
  microserviceauth:
    build: .
    ports:
      - "8001:8080"
    environment:
      - DB_HOST=db_auth  
      - DB_PORT=3306   
      - DB_USER=root
      - DB_PASSWORD=rootpassword  
      - DB_NAME=auth_db
    depends_on:
      db_auth:
        condition: service_healthy
    restart: unless-stopped

  db_auth:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: auth_db
    ports:
      - "3309:3306"  
    volumes:
      - db_auth_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 10
volumes:
  db_auth_data: