version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=usuarios_db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: usuarios_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./usuarios_db.sql:/docker-entrypoint-initdb.d/usuarios_db.sql

volumes:
  db_data:
