version: '3.8'

services:



  frontend-service:
    build: ./frontend
    container_name: frontend-service
    depends_on:
      - usuarios-service
      - reservas-service
    networks:
      backend-net:
        aliases:
          - frontend  


  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    networks:
      - backend-net



############################## USUARIOS ##########################################
  

  usuarios-db:
    image: mysql:8
    container_name: usuarios-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: usuariosdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - usuarios_db_data:/var/lib/mysql
    networks:
      - backend-net



  usuarios-service:
    build: ./services/usuarios-service
    container_name: usuarios-service
    env_file: ./services/usuarios-service/.env
    depends_on:
      - usuarios-db
    ports:
      - "4001:3001"
    networks:
      - backend-net



############################## RESERVAS ##########################################
  

  reservas-db:
    image: postgres:15
    container_name: reservas-db
    environment:
      POSTGRES_DB: reservasdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - reservas_db_data:/var/lib/postgresql/data
    networks:
      - backend-net

  reservas-service:
    build: ./services/reservas-service
    container_name: reservas-service
    env_file: ./services/reservas-service/.env
    depends_on:
      - reservas-db
      - usuarios-service
    ports:
      - "4002:3002"
    networks:
      - backend-net



############################## ESPECIALIDADES ##########################################
  
  especialidades-db:
    image: mongo:6
    container_name: especialidades-db
    ports:
      - "27018:27017"
    volumes:
      - especialidades_db_data:/data/db
    networks:
      - backend-net

  especialidades-service:
    build: ./services/especialidades-agenda-service
    container_name: especialidades-agenda-service
    env_file: ./services/especialidades-agenda-service/.env
    depends_on:
      - especialidades-db
      - usuarios-service   # asegurar que exista este servicio en tu entorno
    ports:
      - "4003:3003"
    networks:
      - backend-net




volumes:
  usuarios_db_data:
  reservas_db_data:
  especialidades_db_data:

networks:
  backend-net:
    driver: bridge